export const MEDIA_CONTENT_KINDS = {
  VIDEO: 'VIDEO',
  DOCUMENT: 'DOCUMENT',
} as const;

export const MEDIA_ACCESS_MODES = {
  DIRECT_URL: 'DIRECT_URL',
  BACKEND_PROXY: 'BACKEND_PROXY',
} as const;

export const MEDIA_VIDEO_LINK_MODES = {
  EMBED: 'embed',
  DIRECT: 'direct',
} as const;

export const MEDIA_DOCUMENT_LINK_MODES = {
  VIEW: 'view',
  DOWNLOAD: 'download',
} as const;

export const MEDIA_ACCESS_MEMBERSHIP_ACTIONS = {
  GRANT: 'GRANT',
  REVOKE: 'REVOKE',
} as const;

export const MEDIA_ACCESS_JOB_NAMES = {
  SYNC_MEMBERSHIP: 'SYNC_MEMBERSHIP',
  SYNC_COURSE_CYCLE_MEMBERSHIP: 'SYNC_COURSE_CYCLE_MEMBERSHIP',
  RECONCILE_SCOPES: 'RECONCILE_SCOPES',
  SYNC_STAFF_VIEWERS: 'SYNC_STAFF_VIEWERS',
  RECOVER_EVALUATION_SCOPE: 'RECOVER_EVALUATION_SCOPE',
} as const;

export const MEDIA_ACCESS_STAFF_GROUP_METADATA = {
  NAME: 'Staff viewers',
  DESCRIPTION: 'Acceso viewer global para admins y superadmins',
} as const;

export const MEDIA_ACCESS_DRIVE_FOLDERS = {
  EVALUATIONS_PARENT: 'evaluations',
  COURSE_CYCLES_PARENT: 'course_cycles',
  EVALUATION_VIDEOS: 'videos',
  EVALUATION_DOCUMENTS: 'documentos',
  EVALUATION_ARCHIVED: 'archivado',
  COURSE_CYCLE_INTRO_VIDEO: 'intro_video',
} as const;

export const MEDIA_ACCESS_SYNC_SOURCES = {
  ENROLLMENT_CREATED: 'ENROLLMENT_CREATED',
  ENROLLMENT_CANCELLED: 'ENROLLMENT_CANCELLED',
  ENROLLMENT_CREATED_COURSE_CYCLE: 'ENROLLMENT_CREATED_COURSE_CYCLE',
  ENROLLMENT_CANCELLED_COURSE_CYCLE: 'ENROLLMENT_CANCELLED_COURSE_CYCLE',
  EVALUATION_CREATED_BANK: 'EVALUATION_CREATED_BANK',
  EVALUATION_CREATED_FULL: 'EVALUATION_CREATED_FULL',
  PROFESSOR_ASSIGNED_COURSE_CYCLE: 'PROFESSOR_ASSIGNED_COURSE_CYCLE',
  PROFESSOR_REVOKED_COURSE_CYCLE: 'PROFESSOR_REVOKED_COURSE_CYCLE',
  USER_STATUS_CHANGE: 'USER_STATUS_CHANGE',
  USERS_ROLE_CHANGE_IMMEDIATE: 'USERS_ROLE_CHANGE_IMMEDIATE',
  RECONCILIATION: 'RECONCILIATION',
  ADMIN_MANUAL_RECOVERY: 'ADMIN_MANUAL_RECOVERY',
} as const;

export const GOOGLE_WORKSPACE_GROUP_ROLES = {
  MEMBER: 'MEMBER',
  MANAGER: 'MANAGER',
  OWNER: 'OWNER',
} as const;

export type GoogleWorkspaceGroupRole =
  (typeof GOOGLE_WORKSPACE_GROUP_ROLES)[keyof typeof GOOGLE_WORKSPACE_GROUP_ROLES];

export function isGoogleGroupMemberRemovable(role?: string): boolean {
  const normalized = String(role || '')
    .trim()
    .toUpperCase();
  return (
    normalized === GOOGLE_WORKSPACE_GROUP_ROLES.MEMBER || normalized === ''
  );
}

export type MediaContentKind =
  (typeof MEDIA_CONTENT_KINDS)[keyof typeof MEDIA_CONTENT_KINDS];
export type MediaAccessMode =
  (typeof MEDIA_ACCESS_MODES)[keyof typeof MEDIA_ACCESS_MODES];
export type MediaVideoLinkMode =
  (typeof MEDIA_VIDEO_LINK_MODES)[keyof typeof MEDIA_VIDEO_LINK_MODES];
export type MediaDocumentLinkMode =
  (typeof MEDIA_DOCUMENT_LINK_MODES)[keyof typeof MEDIA_DOCUMENT_LINK_MODES];
export type MediaAccessMembershipAction =
  (typeof MEDIA_ACCESS_MEMBERSHIP_ACTIONS)[keyof typeof MEDIA_ACCESS_MEMBERSHIP_ACTIONS];
